name: .NET

on:
  push:
    branches: [ master ]
    tags:
      - "*"
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
    - name: Restore dependencies
        run: dotnet restore --source "https://www.nuget.org/api/v2/" --source "http://nuget.episerver.com/feed/packages.svc/"
    - name: Build
        run: dotnet build --no-restore --configuration Release
    - name: Get version from tag
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: |
            echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Publish
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          dotnet nuget add source --username dmytroduk --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dmytroduk/index.json"
          dotnet nuget push "src/Duk.Episerver.Profiles.MultiUserDevice/bin/Release/Duk.Episerver.Profiles.MultiUserDevice.${{ steps.get_version.outputs.VERSION }}.nupkg" --source "github"
    - name: Release    
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "src/Duk.Episerver.Profiles.MultiUserDevice/bin/Release/Duk.Episerver.Profiles.MultiUserDevice.${{ steps.get_version.outputs.VERSION }}.nupkg"
          token: ${{ secrets.GITHUB_TOKEN }}