name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore --source "https://www.nuget.org/api/v2/" --source "http://nuget.episerver.com/feed/packages.svc/"
    - name: Build
      run: dotnet build --no-restore
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "/home/runner/work/Duk.Episerver.Profiles.MultiUserDevice/Duk.Episerver.Profiles.MultiUserDevice/src/Duk.Episerver.Profiles.MultiUserDevice/bin/Debug/Duk.Episerver.Profiles.MultiUserDevice.1.0.0.nupkg"
        token: ${{ secrets.GITHUB_TOKEN }}